"""
synthetic_core.py — VOS v0.5.0 unified runtime.

SyntheticCore wires together TensorEngine, ChaosSparkMemory, and
VictorianGenome into a single, stateful processing unit.  Each call to
:py:meth:`process` ingests the input data into memory, optionally
compresses the hot cache, and returns an enriched output dict.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional

from vos_core.tensor_accel import TensorEngine
from vos_core.chaos_spark_memory import ChaosSparkMemory
from vos_core.victorian_genome import VictorianGenome

logger = logging.getLogger(__name__)


class SyntheticCore:
    """Unified VOS v0.5.0 processing runtime.

    Parameters
    ----------
    device:
        Hardware device for :class:`~vos_core.tensor_accel.TensorEngine`
        (``"cuda"``, ``"cpu"``, etc.).  Auto-selected when *None*.
    memory_capacity:
        Maximum hot-cache entries for
        :class:`~vos_core.chaos_spark_memory.ChaosSparkMemory`.
    compression_ratio:
        Fraction of vector dimensions retained during cache compression.
    db_path:
        SQLite persistence path for the memory store.
    lineage_path:
        JSON lineage file path for the generative genome.
    compress_every:
        Compress the memory hot cache every *N* :py:meth:`process` calls.
        Set to ``0`` to disable automatic compression.
    """

    def __init__(
        self,
        device: Optional[str] = None,
        memory_capacity: int = 512,
        compression_ratio: float = 0.5,
        db_path: str = "vos_memory.db",
        lineage_path: str = "vos_lineage.json",
        compress_every: int = 50,
    ) -> None:
        self.tensor = TensorEngine(device=device)
        self.memory = ChaosSparkMemory(
            capacity=memory_capacity,
            compression_ratio=compression_ratio,
            db_path=db_path,
        )
        self.genome = VictorianGenome(lineage_path=lineage_path)
        self._compress_every = compress_every
        self._call_count: int = 0

        logger.info(
            "SyntheticCore initialised — device=%s capacity=%d compress_every=%d",
            self.tensor.device,
            memory_capacity,
            compress_every,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def process(self, data: Any, **kwargs: Any) -> Dict[str, Any]:
        """Process *data* through the full VOS pipeline.

        1. Ingest *data* into :attr:`memory`.
        2. Trigger hot-cache compression every ``compress_every`` calls.
        3. Return an output dict with standard VOS keys plus any extra
           fields generated by sub-modules.

        Parameters
        ----------
        data:
            Any JSON-serialisable payload (audio features, embeddings, …).
        **kwargs:
            Additional key/value pairs merged verbatim into the output.

        Returns
        -------
        dict
            Output dictionary containing at minimum:

            * ``"input"`` — the original *data*
            * ``"memory_key"`` — storage key assigned by :attr:`memory`
            * ``"memory_status"`` — snapshot from :attr:`memory`
            * ``"genome"`` — current genome expression
        """
        self._call_count += 1

        memory_key = self.memory.ingest(data)

        # Periodic hot-cache compression
        memory_status_str = "stored"
        if self._compress_every > 0 and self._call_count % self._compress_every == 0:
            result = self.memory.compress_hot_cache(tensor_engine=self.tensor)
            memory_status_str = f"compressed:{result}"
            logger.info(
                "SyntheticCore: compression triggered at call %d — %s",
                self._call_count,
                result,
            )

        output: Dict[str, Any] = {
            "input": data,
            "memory_key": memory_key,
            "memory_status": memory_status_str,
            "genome": self.genome.express(),
        }
        output.update(kwargs)
        return output

    def close(self) -> None:
        """Release resources held by sub-modules."""
        self.memory.close()
        logger.info("SyntheticCore closed.")
